<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-08-15 12:29
=======
# Generated by Django 5.2.4 on 2025-08-15 23:31
>>>>>>> 157350b (Implement DRF token authentication and permissions)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
<<<<<<< HEAD
                ('published', models.DateField()),
=======
                ('published_date', models.DateField()),
>>>>>>> 157350b (Implement DRF token authentication and permissions)
            ],
        ),
    ]
